windows_container:
  image_family: pg-ci-windows-ci

visual_studio_2015_aka_14_task:
  system_info_script:
    - systeminfo
  test_script:
    - cd "c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC"
    - vcvarsall.bat x86
    - cd C:/Users/ContainerAdministrator/AppData/Local/Temp/cirrus-ci-build
    - cl /EHsc test.c
    - test.exe

# Clues about selecting the C runtime from:
# https://www.msys2.org/docs/ci/
# https://www.msys2.org/docs/environments/

mingw_ucrt_task:
  env:
    BASH: C:\msys64\usr\bin\bash.exe
    MSYSTEM: UCRT64
  system_info_script: |
    %BASH% -lc 'gcc --version'
  test_script: |
    %BASH% -lc 'gcc test.c -o test'
    %BASH% -lc 'test.exe'

mingw_msvcrt_task:
  env:
    BASH: C:\msys64\usr\bin\bash.exe
    MSYSTEM: MINGW64
  system_info_script: |
    %BASH% -lc 'gcc --version'
  test_script: |
    %BASH% -lc 'gcc test.c -o test'
    %BASH% -lc 'test.exe'
